DROP TABLE IF EXISTS JAVA_CHAMPION;

CREATE TABLE JAVA_CHAMPION (
  id INT(10)   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  last_name VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  year INT(10) NOT NULL
);